### ISSUE TITLE
Cannot find Module 'rollup_plugin_terser'

### ISSUE THREAD

**Issue by Lilith1410** [social-dist0rtion-protocol/thc#5]
I run Ubuntu 18.04. Bash on Windows and I use Ganache instead of Ethnode. 

I followed the instructions to install the dependencies of the folder. IPFS is running in the background, as is Ganache. 
"Make backend" ran without problems, contracts are locally deployed. 
Then I cd'ed into "app" folder and ran "npm start" and I am presented with this Error Message: 

Error: Cannot find module 'rollup-plugin-terser' 
  at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
[...]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-simple-template@0.0.1 start: `rollup --sourcemap --watch --config`
npm ERR! Exit status 1
[...] 

Any ideas on how I can resolve this?

**Comment by TimDaub** [comment]
Looks like rollup-plugin-terser is used in rollup's build process.
However, it's not listed as a development dependency.

Can you try:

```
$ npm i --save-dev rollup-plugin-terser
```

If it works, please also submit the potential fix as a PR!

**Comment by Lilith1410** [comment]
That worked :) thanks tim!
